import type { Metadata } from "next";
import { Public_Sans, Sora } from "next/font/google";
import "./globals.css";

const publicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-public-sans",
});

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",   
  verification: {
     google: "hKYuII4H6m5JC45u8-7sSoyT-al0UjVInpyyPj_QoEk",
   },
};



export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
  lang="en"
  className={`${publicSans.variable} ${sora.variable} h-full`}
>
  <body className="min-h-full flex flex-col font-body bg-cream text-gray-900 antialiased">
    {children}
  </body>
</html>
     );
   }